networks:
  enblitz:
    external: true

# volumes:
#   jenkins_home:
#   grafana-data:
#     driver: local
#   prometheus-data:
#     driver: local
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp:
#   sonar_db:
#   sonar_db_data:
#   portainer_data:

services:
  enblitz-web:
    image: enblitztechnologies/website:v0.0.1
    container_name: enblitz-web
    ports:
      - "3000:80"
    networks:
      - enblitz

  lsses-web:
    image: enblitztechnologies/lsses_web:latest
    container_name: lsses-web
    ports:
      - "8010:8000"
    environment:
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST_USER='shahjainam6411@gmail.com'
      - EMAIL_HOST='smtp.gmail.com'
      - EMAIL_PORT='587'
      - EMAIL_HOST_PASSWORD='arqulqpojmtzjxit'
      - EMAIL_USE_TLS='true'
      - RAZORPAY_API_KEY='rzp_test_I9DANSLk2wH5Ib'
      - RAZORPAY_API_SECRET_KEY='F60ZYATM2RmiaMU4ptOOIpGx'

  wooden-craft-app:
    image:  enblitztechnologies/wooden-craft:latest
    container_name: wooden-craft-app
    ports:
      - "5001:3000"

  next-home-finder-app:
    image:  enblitztechnologies/next-home-finder:dev
    container_name: next-home-finder-app
    ports:
      - "3010:3000"

  version: '3'

  frontend:
    container_name: foodstore-frontend 
    image: enblitztechnologies/eatfront 
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - frontend   

  backend:
    container_name: foodstore-backend  
    image: enblitztechnologies/eatback:latest
    working_dir: /app/backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    networks:
      - frontend  

  networks:
    frontend:

  cartopia-shopping-web:
    image: enblitztechnologies/cartopia:frontend
    container_name: cartopia-shopping-web
    ports:
      - "8084:80"
    depends_on:
      - cartopia-shopping-db
    restart: always

  cartopia-shopping-db:
    image: enblitztechnologies/cartopia:backend
    container_name: cartopia-shopping-db
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3309:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    restart: always
