networks:
  enblitz:
    external: true

# volumes:
#   jenkins_home:
#   grafana-data:
#     driver: local
#   prometheus-data:
#     driver: local
#   sonarqube_conf:
#   sonarqube_data:
#   sonarqube_extensions:
#   sonarqube_logs:
#   sonarqube_temp:
#   sonar_db:
#   sonar_db_data:
#   portainer_data:
version: '3'
services:
  enblitz-web:
    image: enblitztechnologies/website:v0.0.1
    container_name: enblitz-web
    ports:
      - "3000:80"
    networks:
      - enblitz

  # ecommercefinal:
  #   image: enblitztechnologies/ecommercefinal
  #   container_name: ecommercefinal
  #   ports:
  #     - "8090:8090"

  lsses-web:
    image: enblitztechnologies/lsses_web:latest
    container_name: lsses-web
    ports:
      - "8010:8000"
    environment:
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST_USER='shahjainam6411@gmail.com'
      - EMAIL_HOST='smtp.gmail.com'
      - EMAIL_PORT='587'
      - EMAIL_HOST_PASSWORD='arqulqpojmtzjxit'
      - EMAIL_USE_TLS='true'
      - RAZORPAY_API_KEY='rzp_test_I9DANSLk2wH5Ib'
      - RAZORPAY_API_SECRET_KEY='F60ZYATM2RmiaMU4ptOOIpGx'

  wooden-craft-app:
    image:  enblitztechnologies/wooden-craft:latest
    container_name: wooden-craft-app
    ports:
      - "5001:3000"

  next-home-finder-app:
    image:  enblitztechnologies/next-home-finder:dev
    container_name: next-home-finder-app
    ports:
      - "3010:3000"

  eathappy-frontend:
    image: enblitztechnologies/eatfront # Use Node.js version 18
    working_dir: /app/auth-client
    container_name: foodstore-frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development

  eathappy-backend:
    image: enblitztechnologies/eatback:latest # Use Node.js version 16.20.1
    working_dir: /app/auth-server
    container_name: eathappy-auth-server
    ports:
      - "8020:8000"
    depends_on:
      - eathappy-frontend

  cartopia-shopping-web:
    image: enblitztechnologies/cartopia:frontend
    container_name: cartopia-shopping-web
    ports:
      - "8084:80"
    environment:
      - DB_HOST=cartopia-shopping-db
      - DB_USER=example_user
      - DB_PASSWORD=example_password
      - DB_NAME=onlineshop
    restart: always

  cartopia-shopping-db:
    image: enblitztechnologies/cartopia:backend
    container_name: cartopia-shopping-db
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    ports:
      - "3309:3306"
    volumes:
      - ./data:/var/lib/mysql
    restart: always
