networks:
  devops:
    driver: bridge

volumes:
  prometheus-data:
    driver: local

version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    networks:
      - devops
    ports:
      - 9090:9090
