global:
  scrape_interval: 15s
scrape_configs:
 - job_name: prometheus
   honor_timestamps: false
   static_configs:
    - targets:
       - prometheus:9090
  - job_name: 'nodeexporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['nodeexporter:9100']
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
